disable husky, add locales
disabled husky due to garbage typecheck errors: .vitepress/theme/index.ts(8,8): error TS2882: Cannot find module or type declarations for side-effect import of 'virtual:uno.css'.
. typecheck: .vitepress/theme/index.ts(14,8): error TS2882: Cannot find module or type declarations for side-effect import of './custom.css'.
. typecheck: src/client/components/events/BiweeklyCalendar.vue(14,8): error TS2882: Cannot find module or type declarations for side-effect import of 'v-calendar/style.css'.
. typecheck: Failed